echo "We are trying this practical from Linux EC2."
echo "We are from batch-33 and learning git/GitHub."
echo "We are learning Branching."
echo "I am learning Git."
echo "I am learning GitHub."
echo "I am learning maven."
echo "I am learning jenkins."