echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching"
echo "I am learning Git"
echo "I am learning GitHub"
echo "This is a new branch - REQ4545"
echo "This is a REQ4545 branch"
